services:
  vote:
    image: javariya/vote:latest
    ports:
      - 5000:80
      
  result:
     image: javariya/result:latest
     ports: 
       - 5001:4000
     
  worker:
     image: javariya/worker:latest
